### PR TITLE
Add run.sh option to avoid downloading the server

### LINKED ISSUE #92: Add option to skip the downloading of the server jar
If you are running locally, you may not want to wait the time to download a new server jar file for each run.  A `-d` don't download options at the `run.sh` level would achieve this goal.

### PR DESCRIPTION
**Pull request by markpollack**
* Note had to add a `sleep 5` command to wait until mysql was really read to serve requests vs. the netcat port test.

Fixes #92

### CODE REVIEW

**Comment by markpollack** [comment]
maybe the wait should happen inside the download() function so that we only pay the 5 second delay when not downloading the server...

**Comment by markpollack** [comment]
specific error I saw w/o the sleep was 

```
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect to localhost:3306: unexpected end of stream, read 0 bytes from 4
```

**Comment by trisberg** [comment]
LGTM, few minor changes - 

Adding test for existing server jar download, forcing download if file doesn't exist

Also moving sleep so it only runs when no download necessary

**Comment by trisberg** [comment]
Merged as commit dcc5703f022338a51bd8c032f3d60a3d4c28ccd4

**Pull request closed without merging**
