### PR TITLE
Removing local caching of server jar

### LINKED ISSUE #23: Improve the download function to support snapshots and different server versions
The current function
```
function download(){
  if [ ! -f "$1/scdf-server.jar" ]; then
    echo "Downloading latest release from $SPRING_CLOUD_DATAFLOW_SERVER_DOWNLOAD_URL"
    wget $SPRING_CLOUD_DATAFLOW_SERVER_DOWNLOAD_URL --progress=bar -O $1/scdf-server.jar
  fi
}
```
if the local file is there, then it is never downloaded again, but the URL could have changed.  Also, we will be needing to download snapshots builds.  How is this handled in the spring cloud brewery project?

### PR DESCRIPTION
**Pull request by viniciusccarvalho**
Fixes #23

### CODE REVIEW

**Comment by cppwfs** [comment]
Do we want to have an option to cache the latest download.  So if testing locally we don't have to keep re-downloading jars?

**Comment by viniciusccarvalho** [comment]
No, after discussing with Pollack, this is the easiest route to make sure we always download the latest.

Alternatives to that are way too complex to implement IMO, comparing to the benefits they may bring.

**Comment by trisberg** [comment]
Maybe we could introduce a new -d switch at some point (don't download, use what's there from last time)

**Comment by cppwfs** [comment]
What @trisberg mentioned was my thought.

**Comment by viniciusccarvalho** [comment]
Sure, there's always a chance for a new PR to add that

**Comment by trisberg** [comment]
LGTM, merging and we can always create a new issue for `-d` switch

**Pull request merged**
