### PR TITLE
Add woodchuck tests

### LINKED ISSUE #77: Add e2e integration tests for stream partitioning
As a developer, I'd like to add e2e tests for stream partitioning.

**Acceptance:**
- Both local and cf-server coverage included
- The famous "wood chuck ..." example is automated
- Verify multiple app instances are spawned and the stateful data lands in the right partition

### PR DESCRIPTION
**Pull request by jvalkeal**
- Fixes #77

### CODE REVIEW

**Comment by trisberg** [comment]
This approach doesn't work for `log` apps on k8s since we deploy multiple log apps and we need to check the logs for all of them. Maybe we need to add additional URLs, one for each deployed instance in the Application class and then check all instances for proper log content.

**Comment by jvalkeal** [comment]
Ah yeah, there's no balancer in k8s. It's essentially same in local but side effect of same log config is that both apps write to same file. This approach is never going to be reliable.

**Comment by trisberg** [comment]
We should change the local apps to include the pid in the logfile, we used to do that, and collect  URLs for all instances so we can check each logfile

**Comment by trisberg** [comment]
Replaced with #120 PR

**Pull request closed without merging**
